### PR TITLE
fixAuthContext

### PR DESCRIPTION
**Pull request by gulshan07dev**
"Fixing the authContext issue. The problem was that when a user tries to log in, the loading loader is not displayed, and after submitting the form, the modal does close."

### CODE REVIEW

**Comment by gxanshu** [comment]
Thank you for your wonderful contribution. it looks all good to me.

but your `.env` file is also including in that commit. are you sure to merge that will my `.env` file?

**Comment by gulshan07dev** [comment]
Yes sure 👍

**Review by gxanshu — APPROVED** [review]
good work 👍.

**Comment by gxanshu** [comment]
its just only a database issue because @gulshan07dev close the database connections.

**Comment by gulshan07dev** [comment]
No problem, already close connection.

**Pull request merged**
